const products=[
 {id:1,name:'Nova X Pro Smartphone',price:24999,old:31999,icon:'📱',rating:'★ 4.5 (2,831)',desc:'A sleek 5G smartphone with a bright display, long battery life and a sharp camera.'},
 {id:2,name:'Wave Pro Wireless Headphones',price:2999,old:4999,icon:'🎧',rating:'★ 4.4 (1,920)',desc:'Comfortable wireless headphones with clear sound and all-day battery.'},
 {id:3,name:'Aura Smartwatch Series 4',price:3499,old:5999,icon:'⌚',rating:'★ 4.3 (4,128)',desc:'Track your activity, messages and daily goals with a stylish smartwatch.'},
 {id:4,name:'Classic Running Shoes',price:1899,old:2999,icon:'👟',rating:'★ 4.6 (765)',desc:'Lightweight everyday running shoes designed for comfort and grip.'},
 {id:5,name:'BrewMate Coffee Maker',price:2199,old:3899,icon:'☕',rating:'★ 4.2 (540)',desc:'Brew a fresh cup at home with simple controls and a compact design.'},
 {id:6,name:'Urban Backpack 25L',price:1299,old:1999,icon:'🎒',rating:'★ 4.5 (1,110)',desc:'A water-resistant backpack with laptop sleeve and organized pockets.'},
 {id:7,name:'Glow Desk Lamp',price:899,old:1499,icon:'💡',rating:'★ 4.4 (621)',desc:'An adjustable LED desk lamp with a warm, comfortable reading light.'},
 {id:8,name:'Home Speaker Mini',price:1699,old:2799,icon:'🔊',rating:'★ 4.1 (3,004)',desc:'A compact speaker for music, calls and quick voice assistance.'}
];
const money=n=>'₹'+n.toLocaleString('en-IN');
const getCart=()=>JSON.parse(localStorage.getItem('abhiMartCart')||'[]');
const setCart=c=>{localStorage.setItem('abhiMartCart',JSON.stringify(c));updateBadge()};
function updateBadge(){const b=document.querySelector('.cart-badge');if(b)b.textContent=getCart().reduce((s,x)=>s+x.qty,0)}
function logged(){return localStorage.getItem('abhiMartUser')==='abhi'}
function header(){const el=document.querySelector('#header');if(!el)return;el.innerHTML=`<nav class="nav"><a class="brand" href="home.html">Abhi<span>Mart</span></a><div class="search"><input id="searchInput" aria-label="Search products" placeholder="Search for products, brands and more"><button class="mic" id="voiceSearch" title="Search by voice" aria-label="Search by voice">🎙️</button><button id="searchButton" aria-label="Search">⌕</button></div><div class="nav-actions"><a href="home.html">Home</a><a href="cart.html">Cart <span class="cart-badge">0</span></a><a href="mailto:panditkartikeymishra0068@gmail.com">Contact</a><a href="#" id="logout">Logout</a></div></nav>`;updateBadge();const input=document.querySelector('#searchInput');input.value=new URLSearchParams(location.search).get('q')||'';document.querySelector('#logout').onclick=e=>{e.preventDefault();localStorage.removeItem('abhiMartUser');location.href='index.html'};const search=()=>{const q=input.value.trim();if(document.querySelector('#products'))renderProducts(q);else location.href='home.html?q='+encodeURIComponent(q)};document.querySelector('#searchButton').onclick=search;input.onkeydown=e=>{if(e.key==='Enter')search()};input.oninput=()=>{if(document.querySelector('#products'))renderProducts(input.value)};document.querySelector('#voiceSearch').onclick=voiceSearch}
function voiceSearch(){const S=window.SpeechRecognition||window.webkitSpeechRecognition;if(!S){const typed=prompt('Voice search needs Chrome and microphone permission. Type your search:');if(typed!==null){const input=document.querySelector('#searchInput');input.value=typed;document.querySelector('#searchButton').click()}return}const r=new S();r.lang='en-IN';r.interimResults=false;r.onstart=()=>document.querySelector('#voiceSearch').textContent='🔴';r.onerror=()=>{document.querySelector('#voiceSearch').textContent='🎙️';alert('Microphone permission was not allowed. Please allow microphone access and try again.')};r.onend=()=>document.querySelector('#voiceSearch').textContent='🎙️';r.onresult=e=>{const input=document.querySelector('#searchInput');input.value=e.results[0][0].transcript;document.querySelector('#searchButton').click()};r.start()}
function add(id){let c=getCart(),x=c.find(i=>i.id===id);x?x.qty++:c.push({id,qty:1});setCart(c)}
function card(p){return `<article class="card"><a href="product.html?id=${p.id}"><div class="product-icon">${p.icon}</div><span class="tag">${Math.round((1-p.price/p.old)*100)}% OFF</span><h3>${p.name}</h3><div><b class="price">${money(p.price)}</b><span class="old">${money(p.old)}</span></div><p class="rating">${p.rating}</p></a><button class="add" onclick="add(${p.id})">Add to cart</button></article>`}
function renderProducts(query=''){const grid=document.querySelector('#products');if(!grid)return;const list=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));grid.innerHTML=list.length?list.map(card).join(''):`<p>No products found. Try another search.</p>`}
function productPage(){const el=document.querySelector('#productPage');if(!el)return;const p=products.find(x=>x.id===+new URLSearchParams(location.search).get('id'))||products[0];el.innerHTML=`<section class="product-detail"><div class="product-icon">${p.icon}</div><div><p class="eyebrow">ABHIMART ASSURED</p><h1>${p.name}</h1><p class="rating">${p.rating}</p><div><b class="price">${money(p.price)}</b> <span class="old">${money(p.old)}</span> <span class="tag">${Math.round((1-p.price/p.old)*100)}% OFF</span></div><p>${p.desc}</p><p><b>Delivery:</b> Free delivery in 2–4 days</p><div class="buy-actions"><button class="primary" onclick="add(${p.id});location.href='cart.html'">Buy now</button><button class="secondary" onclick="add(${p.id})">Add to cart</button></div></div></section>`}
function cartPage(){const el=document.querySelector('#cartContent');if(!el)return;let c=getCart();if(!c.length){el.innerHTML=`<div class="empty"><div style="font-size:50px">🛒</div><h2>Your cart is empty</h2><p>Add something you like and come back here.</p><a class="primary" href="home.html">Continue shopping</a></div>`;return}let total=0;const rows=c.map(x=>{const p=products.find(p=>p.id===x.id);total+=p.price*x.qty;return `<div class="cart-row"><div class="product-icon">${p.icon}</div><div><h3>${p.name}</h3><b>${money(p.price)}</b><br><button class="remove" onclick="removeItem(${p.id})">Remove</button></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div>`}).join('');el.innerHTML=`<div class="cart-layout"><div>${rows}</div><aside class="summary"><h2>Price details</h2><p><span>Items (${c.reduce((s,x)=>s+x.qty,0)})</span><span>${money(total)}</span></p><p><span>Delivery</span><span style="color:#17833b">FREE</span></p><p class="total"><span>Total amount</span><span>${money(total)}</span></p><button class="primary full" onclick="alert('Order placed! This is a frontend demo.')">Place order</button></aside></div>`}
function changeQty(id,n){let c=getCart();let x=c.find(i=>i.id===id);x.qty+=n;if(x.qty<1)c=c.filter(i=>i.id!==id);setCart(c);cartPage()}function removeItem(id){setCart(getCart().filter(x=>x.id!==id));cartPage()}
document.addEventListener('DOMContentLoaded',()=>{if(location.pathname.endsWith('index.html')||location.pathname.endsWith('/')){document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const id=document.querySelector('#userId').value,pass=document.querySelector('#password').value;if(id==='abhi'&&pass==='1234'){localStorage.setItem('abhiMartUser','abhi');location.href='home.html'}else document.querySelector('#loginError').textContent='Incorrect ID or password. Use abhi / 1234.'};return}if(!logged()){location.href='index.html';return}header();renderProducts(new URLSearchParams(location.search).get('q')||'');productPage();cartPage();document.querySelector('#showAll')?.addEventListener('click',()=>renderProducts())});
